title : QuantDynamics
logo: /assets/img/optimal.jpg
description : Quantitative Finance & Computational Mathematics Applications Development

# set theme
theme: jekyll-theme-minimal

# markdown processor
markdown: kramdown

