title : QuantDynamics
logo: /main/assets/img/optimal.jpg
description : Quantitative Finance & Computational Mathematics Applications Development
show_downloads: false

# set theme
theme: jekyll-theme-minimal

# markdown processor
markdown: kramdown

