title : QuantDynamics
logo: /assets/img/logo.png
description : Quantitative Finance & Computational Mathematics Applications Development
url : catalanicd.github.io

show_downloads: false

# set theme
theme: jekyll-theme-minimal

# markdown processor
markdown: kramdown

